"""Regenerate backend/utils/canonical_models_gen.py from the live DB.

For every model_key that appears with 2+ spellings in `pairs`, pin the dominant
(most common) spelling so write-time normalization ([[brand-model-dedup]] Phase
B) stores one consistent spelling. Keys with a single spelling are left out —
canonical_model() falls back to the cleaned input, so unseen models still work.

Run from the sneaker-impact-dash root:  venv/bin/python3 scripts/gen_canonical_models.py
Safe to re-run anytime (read-only on the DB; rewrites only the generated file).
"""
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.utils.brands import is_insole_brand          # noqa: E402
from backend.utils.models import clean_model, model_key   # noqa: E402

OUT = ROOT / "backend" / "utils" / "canonical_models_gen.py"

conn = sqlite3.connect(f"file:{ROOT / 'sneakers.db'}?mode=ro", uri=True)
rows = conn.execute(
    "SELECT COALESCE(final_make, make), COALESCE(final_model, model), COUNT(*) "
    "FROM pairs WHERE COALESCE(final_model, model) NOT IN ('', 'unknown') "
    "AND COALESCE(final_model, model) IS NOT NULL GROUP BY 1, 2").fetchall()

agg = {}                                    # key -> {cleaned spelling: count}
for make, model, cnt in rows:
    if is_insole_brand(make):
        continue
    cleaned = clean_model(model, make)
    key = model_key(cleaned)
    if not key or key == "unknown":
        continue
    agg.setdefault(key, {})
    agg[key][cleaned] = agg[key].get(cleaned, 0) + cnt

pinned = {k: max(sp, key=sp.get) for k, sp in agg.items() if len(sp) > 1}

with open(OUT, "w") as fh:
    fh.write('"""AUTO-GENERATED by scripts/gen_canonical_models.py — do not edit '
             'by hand.\n\nDominant spelling per model_key, for keys observed with '
             '2+ spellings in the\ndataset. Manual fixes belong in '
             'CANONICAL_MODEL_OVERRIDES (backend/utils/models.py),\nwhich wins '
             'over this map. Regenerate periodically as new spellings accumulate.\n'
             '"""\n\nCANONICAL_MODELS = {\n')
    for k in sorted(pinned):
        fh.write(f"    {k!r}: {pinned[k]!r},\n")
    fh.write("}\n")

print(f"wrote {OUT.name}: {len(pinned)} pinned spellings "
      f"(of {len(agg)} distinct model keys)")
